{
  config,
  lib,
  pkgs,
  username,
  ...
}:

# Emacs comes from Homebrew, and the elisp packages from Nix.
let
  inherit (lib.fixedPoints) composeExtensions;
  inherit (lib.lists) singleton;
  inherit (lib.modules) mkIf;
  inherit (lib.strings) readFile;

  # Ghostel vendors Ghostty's Zig build, whose Darwin SDK helper shells out
  # to xcode-select/xcrun. Provide pure build-time shims pointing at Nixpkgs'
  # SDK so the native module can build inside the Nix sandbox.
  appleSdkZigShims = pkgs.runCommand "apple-sdk-zig-shims" { } ''
    mkdir -p "$out/bin"

    cat > "$out/bin/xcode-select" <<'EOF'
    #!${pkgs.runtimeShell}
    if [ "$1" = "--print-path" ]; then
      echo "${pkgs.apple-sdk}/Platforms/MacOSX.platform/Developer"
      exit 0
    fi
    echo "unsupported xcode-select invocation: $*" >&2
    exit 1
    EOF

    cat > "$out/bin/xcrun" <<'EOF'
    #!${pkgs.runtimeShell}
    if [ "$1" = "--sdk" ] && [ "$3" = "--show-sdk-path" ]; then
      echo "${pkgs.apple-sdk.sdkroot}"
      exit 0
    fi
    echo "unsupported xcrun invocation: $*" >&2
    exit 1
    EOF

    chmod +x "$out/bin/xcode-select" "$out/bin/xcrun"
  '';

  darwinOverrides =
    _final: prev:
    let
      ghostelModule = prev.ghostel.module.overrideAttrs (old: {
        nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [
          appleSdkZigShims
          pkgs.apple-sdk
        ];

        env = (old.env or { }) // {
          SDKROOT = pkgs.apple-sdk.sdkroot;
        };
      });
    in
    {
      ghostel = prev.ghostel.overrideAttrs (old: {
        preBuild = ''
          install ${ghostelModule}/lib/libghostel-module${pkgs.stdenv.hostPlatform.extensions.sharedLibrary} \
            ghostel-module${pkgs.stdenv.hostPlatform.extensions.sharedLibrary}
        '';

        passthru = (old.passthru or { }) // {
          module = ghostelModule;
        };
      });
    };

  emacsPkgs = pkgs.emacsPackages.overrideScope (
    composeExtensions config.emacs.packageOverrides darwinOverrides
  );

  compat = emacsPkgs.compat;

  emacsPackageEnv = pkgs.buildEnv {
    name = "homebrew-emacs-packages";
    paths = config.emacs.packages emacsPkgs;
    pathsToLink = [
      "/bin"
      "/share/emacs/site-lisp"
    ];
  };
in
mkIf config.flags.profiles.graphical {
  homebrew.casks = singleton "jimeh/emacs-builds/emacs-app";

  launchd.user.envVariables.DICPATH = "${config.emacs.spellingDictionaries}/share/hunspell";

  home-manager.users.${username}.home.file.".config/emacs/early-init.el".text = ''
    ;;; early-init.el --- Generated Emacs early init -*- lexical-binding: t -*-

    ;;; Commentary:
    ;; Generated by Nix. The checked-in early-init.el is appended below.

    ;;; Code:

    ;; Make Nix-owned Emacs Lisp packages visible to Homebrew Emacs.
    (let ((site-lisp "${emacsPackageEnv}/share/emacs/site-lisp"))
      (when (file-directory-p site-lisp)
        (let ((default-directory (file-name-as-directory site-lisp)))
          (add-to-list 'load-path (directory-file-name default-directory))
          (normal-top-level-add-subdirs-to-load-path))
        ;; Nix exposes package directories directly, but does not
        ;; activate packages through package.el. Load package autoloads
        ;; explicitly so internal extension entrypoints, such as
        ;; lsp-lens--enable, are defined before hooks/timers call them.
        (let ((elpa-dir (expand-file-name "elpa" site-lisp)))
          (when (file-directory-p elpa-dir)
            (dolist (package-dir
                     (directory-files elpa-dir t "\\`[^.]" t))
              (when (file-directory-p package-dir)
                (dolist (autoload-file
                         (directory-files
                          package-dir t "-autoloads\\.el\\'" t))
                  (load autoload-file nil t))))))
        ;; Export the same Nix package load paths to child Emacsen
        ;; started with -Q.
        (let (nix-load-path)
          (dolist (path load-path)
            (when (and path
                       (or (equal path site-lisp)
                           (string-prefix-p
                            (file-name-as-directory site-lisp)
                            path)))
              (push path nix-load-path)))
          (setenv
           "EMACSLOADPATH"
           (mapconcat #'identity
                      (append
                       (nreverse nix-load-path)
                       (let ((existing (getenv "EMACSLOADPATH")))
                         (if (and existing (> (length existing) 0))
                             (list existing)
                           ;; Empty entry preserves Emacs' default load path.
                           (list ""))))
                      path-separator)))))

    (let ((package-bin "${emacsPackageEnv}/bin"))
      (when (file-directory-p package-bin)
        (add-to-list 'exec-path package-bin)))

    ;; Homebrew Emacs bundles Compat, but its built-in package metadata
    ;; advertises the older bundled version. Prefer the Nix-provided
    ;; Compat version in package metadata too.
    (when (boundp 'package--builtin-versions)
      (setf (alist-get 'compat package--builtin-versions)
            (version-to-list "${compat.version}")))

    ${readFile ../common/emacs/early-init.el}
  '';
}
